### ISSUE TITLE
附录 B.3 勘误

### ISSUE THREAD

**Issue by Hagb** [wxflogic/modal-logic#4]
文老师您好，p363 表 B.3.1 第三行右列（ $\lnot\rightarrow$ ）中的  $\pi:\varphi\rightarrow\psi$ 是否应为 $\pi:\lnot(\varphi\rightarrow\psi)$ ？

**Comment by wxflogic** [comment]
是的，非常感谢您的指正！我会将它加到勘误表中。若发现其他问题，欢迎继续指正！

-----
文学锋
Xuefeng Wen

Institute of Logic and Cognition
Department of Philosophy
Sun Yat-sen University
Guangzhou, 510275
China



Hagb (Junyu Guo 郭俊余) ***@***.***> 于2023年7月30日周日 09:55写道：
